package com.nova.po;

public class App {
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column app_list.appid
    *
    * @mbg.generated Thu Dec 07 16:51:05 CST 2017
    */
   private Integer id;
   
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_list.appid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_list.name
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String appname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_list.appid
     *
     * @return the value of app_list.appid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String easyname;
    
    public String getEasyname() {
		return easyname;
	}

	public void setEasyname(String easyname) {
		this.easyname = easyname;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_list.appid
     *
     * @param appid the value for app_list.appid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_list.appid
     *
     * @return the value of app_list.appid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_list.appid
     *
     * @param appid the value for app_list.appid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_list.name
     *
     * @return the value of app_list.name
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_list.name
     *
     * @param appname the value for app_list.name
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }
}