package com.nova.po;

public class AppNumberCurrentplayers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_number_currentplayers.id
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_number_currentplayers.appid
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_number_currentplayers.player_count
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    private Integer playerCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_number_currentplayers.result
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    private Integer result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_number_currentplayers.id
     *
     * @return the value of app_number_currentplayers.id
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_number_currentplayers.id
     *
     * @param id the value for app_number_currentplayers.id
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_number_currentplayers.appid
     *
     * @return the value of app_number_currentplayers.appid
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_number_currentplayers.appid
     *
     * @param appid the value for app_number_currentplayers.appid
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_number_currentplayers.player_count
     *
     * @return the value of app_number_currentplayers.player_count
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    public Integer getPlayerCount() {
        return playerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_number_currentplayers.player_count
     *
     * @param playerCount the value for app_number_currentplayers.player_count
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    public void setPlayerCount(Integer playerCount) {
        this.playerCount = playerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_number_currentplayers.result
     *
     * @return the value of app_number_currentplayers.result
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_number_currentplayers.result
     *
     * @param result the value for app_number_currentplayers.result
     *
     * @mbg.generated Wed Dec 27 16:22:33 CST 2017
     */
    public void setResult(Integer result) {
        this.result = result;
    }
}