package com.nova.po;

public class AppNews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.id
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.gid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.title
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.url
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.is_external_url
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private int isExternalUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.author
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.feedlabel
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String feedlabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.date
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.feedname
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String feedname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.feed_type
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private int feedType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.appid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_news.contents
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String contents;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.id
     *
     * @return the value of app_news.id
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.id
     *
     * @param id the value for app_news.id
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.gid
     *
     * @return the value of app_news.gid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.gid
     *
     * @param gid the value for app_news.gid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.title
     *
     * @return the value of app_news.title
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.title
     *
     * @param title the value for app_news.title
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.url
     *
     * @return the value of app_news.url
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.url
     *
     * @param url the value for app_news.url
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.is_external_url
     *
     * @return the value of app_news.is_external_url
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public int getIsExternalUrl() {
        return isExternalUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.is_external_url
     *
     * @param isExternalUrl the value for app_news.is_external_url
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setIsExternalUrl(int isExternalUrl) {
        this.isExternalUrl = isExternalUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.author
     *
     * @return the value of app_news.author
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.author
     *
     * @param author the value for app_news.author
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.feedlabel
     *
     * @return the value of app_news.feedlabel
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getFeedlabel() {
        return feedlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.feedlabel
     *
     * @param feedlabel the value for app_news.feedlabel
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setFeedlabel(String feedlabel) {
        this.feedlabel = feedlabel == null ? null : feedlabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.date
     *
     * @return the value of app_news.date
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.date
     *
     * @param date the value for app_news.date
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.feedname
     *
     * @return the value of app_news.feedname
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getFeedname() {
        return feedname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.feedname
     *
     * @param feedname the value for app_news.feedname
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setFeedname(String feedname) {
        this.feedname = feedname == null ? null : feedname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.feed_type
     *
     * @return the value of app_news.feed_type
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public int getFeedType() {
        return feedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.feed_type
     *
     * @param feedType the value for app_news.feed_type
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setFeedType(int feedType) {
        this.feedType = feedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.appid
     *
     * @return the value of app_news.appid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.appid
     *
     * @param appid the value for app_news.appid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_news.contents
     *
     * @return the value of app_news.contents
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_news.contents
     *
     * @param contents the value for app_news.contents
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }
}