package com.nova.po;

public class PlayerBans {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_bans.ban_id
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private String banId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_bans.steamid
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private String steamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_bans.communitybanned
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private Integer communitybanned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_bans.vacbanned
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private Integer vacbanned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_bans.numberofvacbans
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private Integer numberofvacbans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_bans.dayssincelastban
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private Integer dayssincelastban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_bans.numberofgamebans
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private Integer numberofgamebans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_bans.economyban
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private String economyban;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_bans.ban_id
     *
     * @return the value of player_bans.ban_id
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public String getBanId() {
        return banId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_bans.ban_id
     *
     * @param banId the value for player_bans.ban_id
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setBanId(String banId) {
        this.banId = banId == null ? null : banId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_bans.steamid
     *
     * @return the value of player_bans.steamid
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public String getSteamid() {
        return steamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_bans.steamid
     *
     * @param steamid the value for player_bans.steamid
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setSteamid(String steamid) {
        this.steamid = steamid == null ? null : steamid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_bans.communitybanned
     *
     * @return the value of player_bans.communitybanned
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public Integer getCommunitybanned() {
        return communitybanned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_bans.communitybanned
     *
     * @param communitybanned the value for player_bans.communitybanned
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setCommunitybanned(Integer communitybanned) {
        this.communitybanned = communitybanned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_bans.vacbanned
     *
     * @return the value of player_bans.vacbanned
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public Integer getVacbanned() {
        return vacbanned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_bans.vacbanned
     *
     * @param vacbanned the value for player_bans.vacbanned
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setVacbanned(Integer vacbanned) {
        this.vacbanned = vacbanned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_bans.numberofvacbans
     *
     * @return the value of player_bans.numberofvacbans
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public Integer getNumberofvacbans() {
        return numberofvacbans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_bans.numberofvacbans
     *
     * @param numberofvacbans the value for player_bans.numberofvacbans
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setNumberofvacbans(Integer numberofvacbans) {
        this.numberofvacbans = numberofvacbans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_bans.dayssincelastban
     *
     * @return the value of player_bans.dayssincelastban
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public Integer getDayssincelastban() {
        return dayssincelastban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_bans.dayssincelastban
     *
     * @param dayssincelastban the value for player_bans.dayssincelastban
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setDayssincelastban(Integer dayssincelastban) {
        this.dayssincelastban = dayssincelastban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_bans.numberofgamebans
     *
     * @return the value of player_bans.numberofgamebans
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public Integer getNumberofgamebans() {
        return numberofgamebans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_bans.numberofgamebans
     *
     * @param numberofgamebans the value for player_bans.numberofgamebans
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setNumberofgamebans(Integer numberofgamebans) {
        this.numberofgamebans = numberofgamebans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_bans.economyban
     *
     * @return the value of player_bans.economyban
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public String getEconomyban() {
        return economyban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_bans.economyban
     *
     * @param economyban the value for player_bans.economyban
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setEconomyban(String economyban) {
        this.economyban = economyban == null ? null : economyban.trim();
    }
}