package com.nova.po;

public class PlayerSteamLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_steam_level.slevel_id
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private String levelId;

    public String getLevelId() {
		return levelId;
	}

	public void setLevelId(String levelId) {
		this.levelId = levelId;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_steam_level.player_level
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    private Integer playerLevel;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_steam_level.player_level
     *
     * @return the value of player_steam_level.player_level
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public Integer getPlayerLevel() {
        return playerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_steam_level.player_level
     *
     * @param playerLevel the value for player_steam_level.player_level
     *
     * @mbg.generated Fri Dec 15 15:30:19 CST 2017
     */
    public void setPlayerLevel(Integer playerLevel) {
        this.playerLevel = playerLevel;
    }
}