package com.nova.po;

public class PlayerOwnedGames {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_owned_games.ownedga_id
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    private String ownedgaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_owned_games.appid
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_owned_games.appname
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    private String appname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_owned_games.playtime_forever
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    private Integer playtimeForever;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_owned_games.img_icon_url
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    private String imgIconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_owned_games.img_logo_url
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    private String imgLogoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_owned_games.has_community_visible_stats
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    private Integer hasCommunityVisibleStats;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_owned_games.ownedga_id
     *
     * @return the value of player_owned_games.ownedga_id
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public String getOwnedgaId() {
        return ownedgaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_owned_games.ownedga_id
     *
     * @param ownedgaId the value for player_owned_games.ownedga_id
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public void setOwnedgaId(String ownedgaId) {
        this.ownedgaId = ownedgaId == null ? null : ownedgaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_owned_games.appid
     *
     * @return the value of player_owned_games.appid
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_owned_games.appid
     *
     * @param appid the value for player_owned_games.appid
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_owned_games.appname
     *
     * @return the value of player_owned_games.appname
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_owned_games.appname
     *
     * @param appname the value for player_owned_games.appname
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_owned_games.playtime_forever
     *
     * @return the value of player_owned_games.playtime_forever
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public Integer getPlaytimeForever() {
        return playtimeForever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_owned_games.playtime_forever
     *
     * @param playtimeForever the value for player_owned_games.playtime_forever
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public void setPlaytimeForever(Integer playtimeForever) {
        this.playtimeForever = playtimeForever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_owned_games.img_icon_url
     *
     * @return the value of player_owned_games.img_icon_url
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public String getImgIconUrl() {
        return imgIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_owned_games.img_icon_url
     *
     * @param imgIconUrl the value for player_owned_games.img_icon_url
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public void setImgIconUrl(String imgIconUrl) {
        this.imgIconUrl = imgIconUrl == null ? null : imgIconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_owned_games.img_logo_url
     *
     * @return the value of player_owned_games.img_logo_url
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public String getImgLogoUrl() {
        return imgLogoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_owned_games.img_logo_url
     *
     * @param imgLogoUrl the value for player_owned_games.img_logo_url
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public void setImgLogoUrl(String imgLogoUrl) {
        this.imgLogoUrl = imgLogoUrl == null ? null : imgLogoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_owned_games.has_community_visible_stats
     *
     * @return the value of player_owned_games.has_community_visible_stats
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public Integer getHasCommunityVisibleStats() {
        return hasCommunityVisibleStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_owned_games.has_community_visible_stats
     *
     * @param hasCommunityVisibleStats the value for player_owned_games.has_community_visible_stats
     *
     * @mbg.generated Wed Dec 20 12:08:37 CST 2017
     */
    public void setHasCommunityVisibleStats(Integer hasCommunityVisibleStats) {
        this.hasCommunityVisibleStats = hasCommunityVisibleStats;
    }
}