package com.nova.po;

public class PlayerStatsForGame {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_stats_for_game.id
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_stats_for_game.stats_id
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    private String statsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_stats_for_game.appid
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_stats_for_game.name
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_stats_for_game.value
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_stats_for_game.id
     *
     * @return the value of player_stats_for_game.id
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_stats_for_game.id
     *
     * @param id the value for player_stats_for_game.id
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_stats_for_game.stats_id
     *
     * @return the value of player_stats_for_game.stats_id
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public String getStatsId() {
        return statsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_stats_for_game.stats_id
     *
     * @param statsId the value for player_stats_for_game.stats_id
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public void setStatsId(String statsId) {
        this.statsId = statsId == null ? null : statsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_stats_for_game.appid
     *
     * @return the value of player_stats_for_game.appid
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_stats_for_game.appid
     *
     * @param appid the value for player_stats_for_game.appid
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_stats_for_game.name
     *
     * @return the value of player_stats_for_game.name
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_stats_for_game.name
     *
     * @param name the value for player_stats_for_game.name
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_stats_for_game.value
     *
     * @return the value of player_stats_for_game.value
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_stats_for_game.value
     *
     * @param value the value for player_stats_for_game.value
     *
     * @mbg.generated Tue Jan 09 12:53:48 CST 2018
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}