package com.nova.po;

public class PlayerRecentlyPlayedGames {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recently_played_games.recpyga_id
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    private String recpygaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recently_played_games.appid
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    private Integer appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recently_played_games.appname
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    private String appname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recently_played_games.playtime_2weeks
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    private Integer playtime2weeks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recently_played_games.playtime_forever
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    private Integer playtimeForever;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recently_played_games.img_icon_url
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    private String imgIconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_recently_played_games.img_logo_url
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    private String imgLogoUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recently_played_games.recpyga_id
     *
     * @return the value of player_recently_played_games.recpyga_id
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public String getRecpygaId() {
        return recpygaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recently_played_games.recpyga_id
     *
     * @param recpygaId the value for player_recently_played_games.recpyga_id
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public void setRecpygaId(String recpygaId) {
        this.recpygaId = recpygaId == null ? null : recpygaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recently_played_games.appid
     *
     * @return the value of player_recently_played_games.appid
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recently_played_games.appid
     *
     * @param appid the value for player_recently_played_games.appid
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recently_played_games.appname
     *
     * @return the value of player_recently_played_games.appname
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recently_played_games.appname
     *
     * @param appname the value for player_recently_played_games.appname
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public void setAppname(String appname) {
        this.appname = appname == null ? null : appname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recently_played_games.playtime_2weeks
     *
     * @return the value of player_recently_played_games.playtime_2weeks
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public Integer getPlaytime2weeks() {
        return playtime2weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recently_played_games.playtime_2weeks
     *
     * @param playtime2weeks the value for player_recently_played_games.playtime_2weeks
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public void setPlaytime2weeks(Integer playtime2weeks) {
        this.playtime2weeks = playtime2weeks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recently_played_games.playtime_forever
     *
     * @return the value of player_recently_played_games.playtime_forever
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public Integer getPlaytimeForever() {
        return playtimeForever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recently_played_games.playtime_forever
     *
     * @param playtimeForever the value for player_recently_played_games.playtime_forever
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public void setPlaytimeForever(Integer playtimeForever) {
        this.playtimeForever = playtimeForever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recently_played_games.img_icon_url
     *
     * @return the value of player_recently_played_games.img_icon_url
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public String getImgIconUrl() {
        return imgIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recently_played_games.img_icon_url
     *
     * @param imgIconUrl the value for player_recently_played_games.img_icon_url
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public void setImgIconUrl(String imgIconUrl) {
        this.imgIconUrl = imgIconUrl == null ? null : imgIconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_recently_played_games.img_logo_url
     *
     * @return the value of player_recently_played_games.img_logo_url
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public String getImgLogoUrl() {
        return imgLogoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_recently_played_games.img_logo_url
     *
     * @param imgLogoUrl the value for player_recently_played_games.img_logo_url
     *
     * @mbg.generated Wed Dec 20 11:11:05 CST 2017
     */
    public void setImgLogoUrl(String imgLogoUrl) {
        this.imgLogoUrl = imgLogoUrl == null ? null : imgLogoUrl.trim();
    }
}