package com.nova.po;

import java.util.Date;

public class PlayerSummaries {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.sum_id
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String sumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.communityvisibilitystate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private Integer communityvisibilitystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.profilestate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private Integer profilestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.personaname
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String personaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.lastlogoff
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private Integer lastlogoff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.commentpermission
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private Integer commentpermission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.profileurl
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String profileurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.avatar
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.avatarmedium
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String avatarmedium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.avatarfull
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String avatarfull;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.personastate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private Integer personastate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.primaryclanid
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String primaryclanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.timecreated
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private Integer timecreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.personastateflags
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    
    private Integer gameid;
    
    public Integer getGameid() {
		return gameid;
	}

	public void setGameid(Integer gameid) {
		this.gameid = gameid;
	}

	private Integer personastateflags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.loccountrycode
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String loccountrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.locstatecode
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private String locstatecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_summaries.loccityid
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    private Integer loccityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.sum_id
     *
     * @return the value of player_summaries.sum_id
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getSumId() {
        return sumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.sum_id
     *
     * @param sumId the value for player_summaries.sum_id
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setSumId(String sumId) {
    	this.sumId = sumId == null ? null : sumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.communityvisibilitystate
     *
     * @return the value of player_summaries.communityvisibilitystate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public Integer getCommunityvisibilitystate() {
        return communityvisibilitystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.communityvisibilitystate
     *
     * @param communityvisibilitystate the value for player_summaries.communityvisibilitystate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setCommunityvisibilitystate(Integer communityvisibilitystate) {
        this.communityvisibilitystate = communityvisibilitystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.profilestate
     *
     * @return the value of player_summaries.profilestate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public Integer getProfilestate() {
        return profilestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.profilestate
     *
     * @param profilestate the value for player_summaries.profilestate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setProfilestate(Integer profilestate) {
        this.profilestate = profilestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.personaname
     *
     * @return the value of player_summaries.personaname
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getPersonaname() {
        return personaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.personaname
     *
     * @param personaname the value for player_summaries.personaname
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setPersonaname(String personaname) {
        this.personaname = personaname == null ? null : personaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.lastlogoff
     *
     * @return the value of player_summaries.lastlogoff
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public Integer getLastlogoff() {
        return lastlogoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.lastlogoff
     *
     * @param lastlogoff the value for player_summaries.lastlogoff
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setLastlogoff(Integer lastlogoff) {
        this.lastlogoff = lastlogoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.commentpermission
     *
     * @return the value of player_summaries.commentpermission
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public Integer getCommentpermission() {
        return commentpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.commentpermission
     *
     * @param commentpermission the value for player_summaries.commentpermission
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setCommentpermission(Integer commentpermission) {
        this.commentpermission = commentpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.profileurl
     *
     * @return the value of player_summaries.profileurl
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getProfileurl() {
        return profileurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.profileurl
     *
     * @param profileurl the value for player_summaries.profileurl
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setProfileurl(String profileurl) {
        this.profileurl = profileurl == null ? null : profileurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.avatar
     *
     * @return the value of player_summaries.avatar
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.avatar
     *
     * @param avatar the value for player_summaries.avatar
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.avatarmedium
     *
     * @return the value of player_summaries.avatarmedium
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getAvatarmedium() {
        return avatarmedium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.avatarmedium
     *
     * @param avatarmedium the value for player_summaries.avatarmedium
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setAvatarmedium(String avatarmedium) {
        this.avatarmedium = avatarmedium == null ? null : avatarmedium.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.avatarfull
     *
     * @return the value of player_summaries.avatarfull
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getAvatarfull() {
        return avatarfull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.avatarfull
     *
     * @param avatarfull the value for player_summaries.avatarfull
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setAvatarfull(String avatarfull) {
        this.avatarfull = avatarfull == null ? null : avatarfull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.personastate
     *
     * @return the value of player_summaries.personastate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public Integer getPersonastate() {
        return personastate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.personastate
     *
     * @param personastate the value for player_summaries.personastate
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setPersonastate(Integer personastate) {
        this.personastate = personastate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.primaryclanid
     *
     * @return the value of player_summaries.primaryclanid
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getPrimaryclanid() {
        return primaryclanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.primaryclanid
     *
     * @param primaryclanid the value for player_summaries.primaryclanid
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setPrimaryclanid(String primaryclanid) {
        this.primaryclanid = primaryclanid == null ? null : primaryclanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.timecreated
     *
     * @return the value of player_summaries.timecreated
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public Integer getTimecreated() {
        return timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.timecreated
     *
     * @param timecreated the value for player_summaries.timecreated
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setTimecreated(Integer timecreated) {
        this.timecreated = timecreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.personastateflags
     *
     * @return the value of player_summaries.personastateflags
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public Integer getPersonastateflags() {
        return personastateflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.personastateflags
     *
     * @param personastateflags the value for player_summaries.personastateflags
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setPersonastateflags(Integer personastateflags) {
        this.personastateflags = personastateflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.loccountrycode
     *
     * @return the value of player_summaries.loccountrycode
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getLoccountrycode() {
        return loccountrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.loccountrycode
     *
     * @param loccountrycode the value for player_summaries.loccountrycode
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setLoccountrycode(String loccountrycode) {
        this.loccountrycode = loccountrycode == null ? null : loccountrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.locstatecode
     *
     * @return the value of player_summaries.locstatecode
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public String getLocstatecode() {
        return locstatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.locstatecode
     *
     * @param locstatecode the value for player_summaries.locstatecode
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setLocstatecode(String locstatecode) {
        this.locstatecode = locstatecode == null ? null : locstatecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_summaries.loccityid
     *
     * @return the value of player_summaries.loccityid
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public Integer getLoccityid() {
        return loccityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_summaries.loccityid
     *
     * @param loccityid the value for player_summaries.loccityid
     *
     * @mbg.generated Thu Dec 14 17:22:55 CST 2017
     */
    public void setLoccityid(Integer loccityid) {
        this.loccityid = loccityid;
    }
}