package com.nova.po;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userphone
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String userphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.steamid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String steamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isAdmin
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private Integer isadmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    private String achid;
    private String banid;
    private String email;
    public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	private String friendid;
    private String groupid;
    private String ownedgamesid;
    private String recpygaid;
    private String statsid;
    private String levelid;
    private String sumid;
   
    

	public String getAchid() {
		return achid;
	}

	public String getLevelid() {
		return levelid;
	}

	public void setLevelid(String levelid) {
		this.levelid = levelid;
	}

	public void setAchid(String achid) {
		this.achid = achid;
	}

	public String getBanid() {
		return banid;
	}

	public void setBanid(String banid) {
		this.banid = banid;
	}

	public String getFriendid() {
		return friendid;
	}

	public void setFriendid(String friendid) {
		this.friendid = friendid;
	}

	public String getGroupid() {
		return groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	public String getOwnedgamesid() {
		return ownedgamesid;
	}

	public void setOwnedgamesid(String ownedgamesid) {
		this.ownedgamesid = ownedgamesid;
	}

	public String getRecpygaid() {
		return recpygaid;
	}

	public void setRecpygaid(String recpygaid) {
		this.recpygaid = recpygaid;
	}

	public String getStatsid() {
		return statsid;
	}

	public void setStatsid(String statsid) {
		this.statsid = statsid;
	}


	public String getSumid() {
		return sumid;
	}

	public void setSumid(String sumid) {
		this.sumid = sumid;
	}

	public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userphone
     *
     * @return the value of user.userphone
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userphone
     *
     * @param userphone the value for user.userphone
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.steamid
     *
     * @return the value of user.steamid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public String getSteamid() {
        return steamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.steamid
     *
     * @param steamid the value for user.steamid
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setSteamid(String steamid) {
        this.steamid = steamid == null ? null : steamid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isAdmin
     *
     * @return the value of user.isAdmin
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public Integer getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isAdmin
     *
     * @param isadmin the value for user.isAdmin
     *
     * @mbg.generated Thu Dec 07 16:51:05 CST 2017
     */
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }
}